// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTenants.IdentityServer.Persistence;

#nullable disable

namespace MultiTenants.IdentityServer.Persistence.Migrations.TenantAdmin
{
    [DbContext(typeof(TenantAdminDbContext))]
    [Migration("20220813173814_FirstMultiTenantMigration")]
    partial class FirstMultiTenantMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MultiTenants.IdentityServer.Domain.Entities.TenantAdmin.MultiTenantInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenIdAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenIdClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenIdClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasFilter("[Identifier] IS NOT NULL");

                    b.ToTable("TenantInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
